### ISSUE TITLE
References to GUI elements

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdevdocs#17]
Copying from #14

https://github.com/jholdstock/dcrdevdocs/pull/14#discussion_r320546370

> Settings -> `Settings`
> 
> I don't think we're very consistent with this (could be a separate Issue), but GUI elements we usually **bold** or `style`.

**Comment by jholdstock** [comment]
Probably want to make these changes in decred/dcrdocs as well

**Comment by s-ben** [comment]
Yup. I have a slight lean towards `styled element names`, but no strong feelings.
