### ISSUE TITLE
Setting up development environment

### ISSUE THREAD

**Issue by s-ben** [decred/dcrdevdocs#36]
I noticed that on dcrdocs, we have some instructions on [setting up a go environment](https://docs.decred.org/contributing/source-code-contributions/#go). In @raedah's notes, we also have this [Learning to code section](https://github.com/raedahgroup/dcrdevdocs/blob/master/start.md#learning-to-code), which recommends a go book (which was also recommended to me by lukebp when I started coding on Politeia). Wondering if we should put this content somewhere? The Contributor Guidelines page? A new page? Thoughts?

**Comment by jholdstock** [comment]
I have mixed feelings about this. Setting up a dev environment can vary quite a bit from repo to repo, even between repos of the same language. eg. The dev env for dcrstakepool is different to dcrd or dcrwallet, even though they are all mostly Go. To me this feels like the sort of thing which should really live in the relevant repository README.

We should definitely document things are generic to all repos - for example the github workflow of fork, clone, branch, commit, push, PR.

**Comment by s-ben** [comment]
Was leaning towards the same. While these are good resources, we don't want to be standardizing on someone's favorite programming book (good as it may be) or repo-specific dev environment setup.
