### ISSUE TITLE
Move over some pages from dcrdocs

### ISSUE THREAD

**Issue by teknico** [decred/dcrdevdocs#46]
The following pages in the dcrdocs repo's Advanced section focus on technical details ostensibly only interesting for developers.

To move here:

* Block Header Specifications

Already moved here, possibly to be deleted from dcrdocs:

* Address Details
* Using Testnet
* Blockchain Parameters
* Transaction Details

The whole Research section should probably be moved here too.

The Contributing section has been already moved here and should probably be replaced by a link to these docs.

**Comment by s-ben** [comment]
Have added the Block Header Specification page (https://github.com/jholdstock/dcrdevdocs/pull/47). Will get a branch going on dcrdocs for removing pages we've ported here. 

>The whole Research section should probably be moved here too.

On the research section, I'm conflicted. I think we could move it all here, but I'm leaning towards leaving it in dcrdocs. The reasoning being that there will be researchers and other power users (e.g. investors, analysts) that won't be writing code, per se. Or don't identify as a developers. The research pages might be more discoverable for them in dcrdocs. Open to having my mind changed.

>The Contributing section has been already moved here and should probably be replaced by a link to these docs.

Right now, the contributing page on dcrdocs deals with contributing generally, the contractor system. Which I think is where we want it, as not all contributors will be developers. The contributing page in the devdocs just talks about the dev-specific contributing stuff and links to dcrdocs, which I think works OK.

**Comment by jholdstock** [comment]
@s-ben please ensure your PR includes:

- removing img_src directory
- removing all of the images
- adding necessary nginx redirects

**Comment by jholdstock** [comment]
This is all done
